baseURL = "https://dannyk20.github.io/"
languageCode = "ko-kr"
title = "Taehoon Devlog"
theme = "hugo-theme-stack"

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  mainSections = ["posts"]
  favicon = "/favicon.ico"

  [params.sidebar]
    avatar = "img/avatar.png" 
    emoji = "ðŸ’»"
    subtitle = "CS Â· Algorithms Â· JavaScript"

  [params.article]
    math = false

  [params.footer]
    since = 2025

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
    identifier = "posts"

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]